---
# Version 3.7 for compose files corresponds with
# Docker engine 18.06.0 and newer (per Docker docs).
version: "3.7"

# Nested dictionary of containers to create. I'm demonstrating
# 3 vlansNMS apps each exposing a different public TCP port. This is
# a "scale out" technique and you could put a load balancer in front.
services:
  vlansNMS1:
    build: "."
    image: "docker.test:latest"
    ports:
      - "5001:5000/tcp"
    volumes:
      - type: "bind"
        source: "./vlansNMS"
        target: "/vlansNMS"
  vlansNMS2:
    image: "docker.test:latest"
    ports:
      - "5002:5000/tcp"
    volumes:
      - type: "bind"
        source: "./vlansNMS"
        target: "/vlansNMS"
  vlansNMS3:
    image: "docker.test:latest"
    ports:
      - "5003:5000/tcp"
    volumes:
      - type: "bind"
        source: "./vlansNMS"
        target: "/vlansNMS"
...
