"""Initial migration

Revision ID: ec35792a504b
Revises: 
Create Date: 2021-03-03 07:49:42.408784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec35792a504b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'vlans', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vlans', type_='unique')
    # ### end Alembic commands ###
